
services:
  - type: web
    name: biocheai
    env: python
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run biocheai/streamlit_admin_ui.py --server.port 10000 --server.enableCORS false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
    autoDeploy: true
